//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestJoin_Tbl
    {
        public int Req_Id { get; set; }
        public string Req_name { get; set; }
        public string Req_Dept { get; set; }
        public string Req_Age { get; set; }
        public int Cat_Fid { get; set; }
    
        public virtual Category_Tbl Category_Tbl { get; set; }
    }
}
