//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamList_Tbl
    {
        public int team_id { get; set; }
        public string member_name { get; set; }
        public string member_batch { get; set; }
        public string member_dept { get; set; }
        public string other_info { get; set; }
        public int Cat_Bid { get; set; }
    
        public virtual Category_Tbl Category_Tbl { get; set; }
    }
}
